### PR TITLE
Fix install script compatibility for systemd based distro's.

### PR DESCRIPTION
**Pull request by rubdos**
Has been tested under Arch Linux, will possibly undergo testing under
CentOS 7 too. Should work™ with most other `systemd` based (host) distro's.

Basically:
- mounts are under /var/run/media, not under /media
- boot becomes BOOT for vfat mounts under some distro's.

### CODE REVIEW

**Comment by rubdos** [comment]
Someone had a look at this? :-)

**Comment by rubdos** [comment]
I rebased this on current master, if still interested.

**Comment by rubdos** [comment]
I rebased this on current master, if still interested.

**Comment by MikeLooijmans** [comment]
Merged with a minor change (comment text).
Thanks for contributing!

**Pull request closed without merging**
